# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-13 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('Telugu', 'Telugu'), ('Marathi', 'Marathi'), ('Tamil', 'Tamil'), ('Kannada', 'Kannada'), ('Hindi', 'Hindi'), ('English', 'English'), ('Punjabi', 'Punjabi'), ('Bengali', 'Bengali')], max_length=64),
        ),
    ]
