# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-11 13:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lyv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalbook',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalparagraph',
            name='book',
        ),
        migrations.RemoveField(
            model_name='historicalparagraph',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalrecording',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalrecording',
            name='paragraph',
        ),
        migrations.AddField(
            model_name='book',
            name='filename',
            field=models.FileField(default=datetime.datetime(2016, 2, 11, 13, 40, 2, 354708, tzinfo=utc), upload_to='books'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='HistoricalBook',
        ),
        migrations.DeleteModel(
            name='HistoricalParagraph',
        ),
        migrations.DeleteModel(
            name='HistoricalRecording',
        ),
    ]
