# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-11 18:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lyv', '0002_auto_20160211_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='filename',
            field=models.FileField(default=datetime.datetime(2016, 2, 11, 18, 3, 30, 643919, tzinfo=utc), upload_to='recordings'),
            preserve_default=False,
        ),
    ]
