# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-11 19:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lyv', '0003_recording_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='para',
            field=models.TextField(default=datetime.datetime(2016, 2, 11, 19, 44, 48, 392614, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
