# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-13 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyv', '0003_auto_20160213_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Tamil', 'Tamil'), ('Bengali', 'Bengali'), ('Telugu', 'Telugu'), ('Kannada', 'Kannada'), ('Marathi', 'Marathi'), ('Punjabi', 'Punjabi')], max_length=64),
        ),
    ]
