# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-11 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lyv', '0004_paragraph_para'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paragraph',
            old_name='para',
            new_name='paragraph',
        ),
    ]
