# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 15:07
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lyv', '0005_auto_20160211_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='recorded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recording',
            name='user',
            field=models.ForeignKey(default=datetime.datetime(2016, 2, 12, 15, 7, 53, 459502, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, related_name='user_recording', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
