# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lyv', '0006_auto_20160212_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recording',
            name='user',
        ),
    ]
